"""Auto-generated by engine.bootstrap.generate (adapter-bootstrap Phase 4)
for "Bootstrap Demo: Purchase" - a DRAFT for human review, not hand-audited. Bootstrap
status: inconclusive.
"""

# ============================================================================
# DRAFT, NOT FULLY CONFIRMED: the adapter-bootstrap probing loop ran out of
# budget before reaching confidence. Known remaining gaps, in its own words:
#
# 
# The OpenAPI spec was successfully retrieved (probe 2), confirming the endpoint is POST /purchase with six required fields: auth_token (string), card_number (string), expiry_month (integer), expiry_year (integer), cvv (string), and credit_count (integer). A live 200 response was obtained (probe 3), confirming the endpoint is reachable and the schema is structurally correct — this counts as a genuine response, though the transaction was declined. The response body structure for declined transactions is confirmed: {status, decline_reason, credits_purchased, total_charged, new_credit_balance, transaction_id}. However, a truly successful (approved) transaction has never been seen, meaning fields like transaction_id and new_credit_balance have only been observed as null. The valid auth_token is unknown. Pydantic-level field constraints (ranges for expiry_month, minimum credit_count) have not been confirmed because omitting auth_token causes only a single 422 for the missing field — suggesting auth_token is validated first and other constraint errors may be masked. The verdict is needs_more_probing because the most critical unknown (valid auth_token for a success response) remains unresolved.
#
# Review this file carefully before trusting it - especially execute_test()
# and the discovered field list below - before running real bug-hunting
# checkpoints against it.
# ============================================================================

from engine.adapter import SUTAdapter
from engine.http import call_sut_once
from engine.report import bool_badge, esc, inline_markdown, render_json_block

BASE_URL = 'http://127.0.0.1:8020'
TEST_ENDPOINT_PATH = '/purchase'
HTTP_METHOD = 'POST'

API_SCHEMA_DOC = "POST /purchase\n\nRequest body:\n  auth_token: string - required - Authentication token required for the purchase. Must be a valid token recognized by the server. Several common values (test-auth-token-abc123, secret, admin) all returned 'invalid_auth_token' decline reason. Valid value not yet discovered.\n  card_number: string - required - Credit/debit card number as a string. Value '4111111111111111' (Visa test number) was accepted at the Pydantic level without a validation error. No format constraints confirmed beyond being a string.\n  expiry_month: integer - required - Card expiry month as an integer. Values 0, 12, and 13 all passed Pydantic validation without a 422 (only the missing auth_token triggered 422). This suggests no min/max Pydantic-level constraint confirmed yet — range 1-12 is suspected but unconfirmed.\n  expiry_year: integer - required - Card expiry year as an integer. Value 2026 used in all probes. No constraints observed.\n  cvv: string - required - Card CVV/security code as a string. Value '123' used in all probes without triggering Pydantic validation errors. No length or format constraints confirmed.\n  credit_count: integer - required - Number of credits to purchase as an integer. Negative values (e.g., -1) and positive values (1, 5, 10) all passed Pydantic validation. No min/max constraint confirmed at the Pydantic level.\n\nThis schema was discovered/confirmed by the adapter-bootstrap tool, not hand-written - review it before trusting it fully."

HAPPY_DAY_REQUEST = {}

_REQUEST_FIELD_NAMES = ['auth_token', 'card_number', 'expiry_month', 'expiry_year', 'cvv', 'credit_count']


def execute_test(test: dict, test_number: int) -> dict:
    request_body = {k: v for k, v in test.items() if k in _REQUEST_FIELD_NAMES}
    request = {"method": HTTP_METHOD, "path": TEST_ENDPOINT_PATH, "body": request_body}

    response = call_sut_once(BASE_URL, TEST_ENDPOINT_PATH, request_body, method=HTTP_METHOD)
    actual_status_family = f"{response['status'] // 100}xx"
    predicted_status_family = test["predicted_status_family"]
    prediction_matched = actual_status_family == predicted_status_family

    return {
        "test_number": test_number,
        "request": request,
        "response": response,
        "predicted_outcome": test["predicted_outcome"],
        "predicted_status_family": predicted_status_family,
        "actual_status_family": actual_status_family,
        "prediction_matched": prediction_matched,
    }


CASTING_TOOL = {'name': 'submit_casting_round',
 'description': 'Propose a batch of tests against the live /purchase endpoint.',
 'input_schema': {'type': 'object',
                  'properties': {'give_up': {'type': 'boolean',
                                             'description': 'Set true only if you have no more '
                                                            'good ideas worth proposing this '
                                                            'round.'},
                                 'reasoning': {'type': 'string',
                                               'description': "Your reasoning for this round's "
                                                              'batch.'},
                                 'candidate_tests': {'type': 'array',
                                                     'description': 'Each is EITHER tied to a '
                                                                    'specific candidate hypothesis '
                                                                    '(set linked_hypothesis to '
                                                                    'that theory) OR a pure '
                                                                    'edge-case probe not tied to '
                                                                    'any theory (empty string).',
                                                     'items': {'type': 'object',
                                                               'properties': {'linked_hypothesis': {'type': 'string'},
                                                                              'auth_token': {'type': 'string',
                                                                                             'description': 'Authentication '
                                                                                                            'token '
                                                                                                            'required '
                                                                                                            'for '
                                                                                                            'the '
                                                                                                            'purchase. '
                                                                                                            'Must '
                                                                                                            'be '
                                                                                                            'a '
                                                                                                            'valid '
                                                                                                            'token '
                                                                                                            'recognized '
                                                                                                            'by '
                                                                                                            'the '
                                                                                                            'server. '
                                                                                                            'Several '
                                                                                                            'common '
                                                                                                            'values '
                                                                                                            '(test-auth-token-abc123, '
                                                                                                            'secret, '
                                                                                                            'admin) '
                                                                                                            'all '
                                                                                                            'returned '
                                                                                                            "'invalid_auth_token' "
                                                                                                            'decline '
                                                                                                            'reason. '
                                                                                                            'Valid '
                                                                                                            'value '
                                                                                                            'not '
                                                                                                            'yet '
                                                                                                            'discovered.'},
                                                                              'card_number': {'type': 'string',
                                                                                              'description': 'Credit/debit '
                                                                                                             'card '
                                                                                                             'number '
                                                                                                             'as '
                                                                                                             'a '
                                                                                                             'string. '
                                                                                                             'Value '
                                                                                                             "'4111111111111111' "
                                                                                                             '(Visa '
                                                                                                             'test '
                                                                                                             'number) '
                                                                                                             'was '
                                                                                                             'accepted '
                                                                                                             'at '
                                                                                                             'the '
                                                                                                             'Pydantic '
                                                                                                             'level '
                                                                                                             'without '
                                                                                                             'a '
                                                                                                             'validation '
                                                                                                             'error. '
                                                                                                             'No '
                                                                                                             'format '
                                                                                                             'constraints '
                                                                                                             'confirmed '
                                                                                                             'beyond '
                                                                                                             'being '
                                                                                                             'a '
                                                                                                             'string.'},
                                                                              'expiry_month': {'type': 'integer',
                                                                                               'description': 'Card '
                                                                                                              'expiry '
                                                                                                              'month '
                                                                                                              'as '
                                                                                                              'an '
                                                                                                              'integer. '
                                                                                                              'Values '
                                                                                                              '0, '
                                                                                                              '12, '
                                                                                                              'and '
                                                                                                              '13 '
                                                                                                              'all '
                                                                                                              'passed '
                                                                                                              'Pydantic '
                                                                                                              'validation '
                                                                                                              'without '
                                                                                                              'a '
                                                                                                              '422 '
                                                                                                              '(only '
                                                                                                              'the '
                                                                                                              'missing '
                                                                                                              'auth_token '
                                                                                                              'triggered '
                                                                                                              '422). '
                                                                                                              'This '
                                                                                                              'suggests '
                                                                                                              'no '
                                                                                                              'min/max '
                                                                                                              'Pydantic-level '
                                                                                                              'constraint '
                                                                                                              'confirmed '
                                                                                                              'yet '
                                                                                                              '— '
                                                                                                              'range '
                                                                                                              '1-12 '
                                                                                                              'is '
                                                                                                              'suspected '
                                                                                                              'but '
                                                                                                              'unconfirmed.'},
                                                                              'expiry_year': {'type': 'integer',
                                                                                              'description': 'Card '
                                                                                                             'expiry '
                                                                                                             'year '
                                                                                                             'as '
                                                                                                             'an '
                                                                                                             'integer. '
                                                                                                             'Value '
                                                                                                             '2026 '
                                                                                                             'used '
                                                                                                             'in '
                                                                                                             'all '
                                                                                                             'probes. '
                                                                                                             'No '
                                                                                                             'constraints '
                                                                                                             'observed.'},
                                                                              'cvv': {'type': 'string',
                                                                                      'description': 'Card '
                                                                                                     'CVV/security '
                                                                                                     'code '
                                                                                                     'as '
                                                                                                     'a '
                                                                                                     'string. '
                                                                                                     'Value '
                                                                                                     "'123' "
                                                                                                     'used '
                                                                                                     'in '
                                                                                                     'all '
                                                                                                     'probes '
                                                                                                     'without '
                                                                                                     'triggering '
                                                                                                     'Pydantic '
                                                                                                     'validation '
                                                                                                     'errors. '
                                                                                                     'No '
                                                                                                     'length '
                                                                                                     'or '
                                                                                                     'format '
                                                                                                     'constraints '
                                                                                                     'confirmed.'},
                                                                              'credit_count': {'type': 'integer',
                                                                                               'description': 'Number '
                                                                                                              'of '
                                                                                                              'credits '
                                                                                                              'to '
                                                                                                              'purchase '
                                                                                                              'as '
                                                                                                              'an '
                                                                                                              'integer. '
                                                                                                              'Negative '
                                                                                                              'values '
                                                                                                              '(e.g., '
                                                                                                              '-1) '
                                                                                                              'and '
                                                                                                              'positive '
                                                                                                              'values '
                                                                                                              '(1, '
                                                                                                              '5, '
                                                                                                              '10) '
                                                                                                              'all '
                                                                                                              'passed '
                                                                                                              'Pydantic '
                                                                                                              'validation. '
                                                                                                              'No '
                                                                                                              'min/max '
                                                                                                              'constraint '
                                                                                                              'confirmed '
                                                                                                              'at '
                                                                                                              'the '
                                                                                                              'Pydantic '
                                                                                                              'level.'},
                                                                              'predicted_outcome': {'type': 'string',
                                                                                                    'description': 'What '
                                                                                                                   'you '
                                                                                                                   'predict '
                                                                                                                   'will '
                                                                                                                   'happen '
                                                                                                                   'and '
                                                                                                                   'why.'},
                                                                              'predicted_status_family': {'type': 'string',
                                                                                                          'enum': ['2xx',
                                                                                                                   '4xx',
                                                                                                                   '5xx'],
                                                                                                          'description': 'The '
                                                                                                                         'broad '
                                                                                                                         'class '
                                                                                                                         'of '
                                                                                                                         'HTTP '
                                                                                                                         'status '
                                                                                                                         'you '
                                                                                                                         'predict '
                                                                                                                         'this '
                                                                                                                         'test '
                                                                                                                         'will '
                                                                                                                         'get '
                                                                                                                         'back.'}},
                                                               'required': ['linked_hypothesis',
                                                                            'auth_token',
                                                                            'card_number',
                                                                            'expiry_month',
                                                                            'expiry_year',
                                                                            'cvv',
                                                                            'credit_count',
                                                                            'predicted_outcome',
                                                                            'predicted_status_family']}}},
                  'required': ['give_up', 'reasoning', 'candidate_tests']}}

_FIRST_ROUND_CONTEXT = """Nothing is currently flagged as anomalous, and you do not know whether any bug
exists at all - this adapter was auto-generated from a discovered/confirmed schema, not hand-audited.
Before proposing anything, think about common bug classes for REST endpoints in general: boundary
values, type coercion issues, validation ordering that leaks information before authorization is
confirmed, off-by-one errors at numeric limits, and inconsistent handling of missing vs. null vs. empty
values. State this reasoning explicitly."""

_LATER_ROUND_CONTEXT = """You now have real test results, and prior_checkpoint_feedback holds the
previous checkpoint's hypothesis plus Skeptic's cold critique of it. If that hypothesis claimed any
anomalies that Skeptic found weak, prioritize tests that could confirm OR refute those SPECIFIC claims.
Briefly state what you've actually learned so far and how that's changing your approach this round."""


def casting_system_prompt(test_budget: int, is_first_round: bool) -> str:
    if is_first_round:
        context_instruction = _FIRST_ROUND_CONTEXT
    else:
        context_instruction = _LATER_ROUND_CONTEXT

    return f"""You are testing a live API endpoint (POST /purchase) to look for
bugs or unexpected behavior. You've been shown the API's schema documentation and one real executed
"happy day" example.

{context_instruction}

In one round, propose a BATCH of tests - up to {test_budget} total:
1. Candidate hypotheses: think of a few specific, falsifiable theories about possible bugs - e.g.
   boundary values, type coercion issues, validation ordering that leaks information before
   authorization is confirmed, off-by-one errors, or inconsistent handling of missing vs. null vs.
   empty values. For each, propose 1-2 concrete test ideas - a full request plus a prediction of what
   would happen if that specific theory were true. Set linked_hypothesis to the full theory text.
2. Pure edge-case probes: also propose tests not tied to any specific theory - general negative-case/
   boundary testing instinct. Predict "2xx" as your null hypothesis and set linked_hypothesis to an
   empty string.

All of these tests will be executed for real, together, before you see any results. If you believe
you've explored reasonably and have no more good ideas worth proposing, set give_up to true rather
than proposing something arbitrary just to have something to submit.

Prioritize breadth over depth. Before proposing a test, check tests_tried_in_earlier_rounds: if the
same underlying question has already been asked multiple times with consistent results, treat it as
settled.

Call submit_casting_round with your answer."""


_JSON_TYPE_TO_PYTHON = {
    "string": str, "integer": int, "number": (int, float),
    "boolean": bool, "array": list, "object": dict,
}

_DISCOVERED_FIELDS = [{'name': 'auth_token', 'type': 'string', 'required': True, 'enum': None},
 {'name': 'card_number', 'type': 'string', 'required': True, 'enum': None},
 {'name': 'expiry_month', 'type': 'integer', 'required': True, 'enum': None},
 {'name': 'expiry_year', 'type': 'integer', 'required': True, 'enum': None},
 {'name': 'cvv', 'type': 'string', 'required': True, 'enum': None},
 {'name': 'credit_count', 'type': 'integer', 'required': True, 'enum': None}]


def validate_casting_response(data) -> list[str]:
    errors = []
    if not isinstance(data, dict):
        return [f"expected an object, got {type(data).__name__}"]

    for key in ("give_up", "reasoning", "candidate_tests"):
        if key not in data:
            errors.append(f"missing required field '{key}'")

    if not isinstance(data.get("give_up"), bool):
        errors.append("'give_up' must be a boolean")

    tests = data.get("candidate_tests")
    if not isinstance(tests, list):
        errors.append("'candidate_tests' must be a list")
    elif not data.get("give_up") and not tests:
        errors.append("'candidate_tests' must be non-empty unless give_up is true")
    else:
        required_keys = ['linked_hypothesis',
 'auth_token',
 'card_number',
 'expiry_month',
 'expiry_year',
 'cvv',
 'credit_count',
 'predicted_outcome',
 'predicted_status_family']
        for i, test in enumerate(tests or []):
            if not isinstance(test, dict):
                errors.append(f"candidate_tests[{i}] must be an object")
                continue
            for key in required_keys:
                if key not in test:
                    errors.append(f"candidate_tests[{i}] missing '{key}'")
            for field_meta in _DISCOVERED_FIELDS:
                name = field_meta["name"]
                if name not in test:
                    continue
                expected_type = _JSON_TYPE_TO_PYTHON.get(field_meta["type"])
                if expected_type is not None and not isinstance(test[name], expected_type):
                    errors.append(f"candidate_tests[{i}].{name} must be of type {field_meta['type']}")
                if field_meta["enum"] and test[name] not in field_meta["enum"]:
                    errors.append(f"candidate_tests[{i}].{name} must be one of {field_meta['enum']}")
            if test.get("predicted_status_family") not in ("2xx", "4xx", "5xx"):
                errors.append(f"candidate_tests[{i}].predicted_status_family must be one of ('2xx', '4xx', '5xx')")

    return errors


def render_test_entry(entry) -> str:
    if not entry:
        return ""
    request = entry.get("request", {})
    body = request.get("body", {})

    linked = entry.get("linked_hypothesis")
    linked_html = f"<strong>Hypothesis:</strong> {esc(linked)}" if linked else (
        '<span class="probe-label">Edge-case probe</span> (no linked hypothesis)'
    )
    test_number = entry.get("test_number")
    number_html = f'<span class="test-number">Test #{esc(test_number)}</span>' if test_number is not None else ""

    predicted = entry.get("predicted_status_family")
    actual = entry.get("actual_status_family")
    matched = entry.get("prediction_matched")

    return f"""
    <article class="test">
      <div class="test-hypothesis">{number_html}{linked_html}</div>
      {render_json_block(body)}
      <div class="test-predicted">Predicted: {inline_markdown(entry.get('predicted_outcome'))}
        <span class="prose-muted">{esc(predicted)}</span></div>
      <div class="test-outcome">
        Actual: <span class="prose-muted">{esc(actual)}</span>
        <span class="sep">&middot;</span> prediction {bool_badge(matched, 'matched', 'missed')}
      </div>
    </article>
    """


def render_onboarding_section(api_schema, onboarding_extra, happy_day_example) -> str:
    happy_request = (happy_day_example or {}).get("request", {})
    happy_response = (happy_day_example or {}).get("response", {})
    return f"""
    <div class="exhibit">
      <h3>API schema</h3>
      <pre class="schema-doc">{esc(api_schema)}</pre>
    </div>
    <div class="exhibit">
      <h3>Happy-day example</h3>
      <p class="eyebrow">Request</p>
      {render_json_block(happy_request.get('body', {}))}
      <p class="eyebrow">Response</p>
      {render_json_block(happy_response.get('body', {}))}
    </div>
    """


ADAPTER = SUTAdapter(
    name='bootstrap_demo_purchase',
    display_name='Bootstrap Demo: Purchase',
    base_url=BASE_URL,
    test_endpoint_path=TEST_ENDPOINT_PATH,
    api_schema_doc=API_SCHEMA_DOC,
    happy_day_request=HAPPY_DAY_REQUEST,
    casting_tool_schema=CASTING_TOOL,
    casting_system_prompt=casting_system_prompt,
    validate_casting_response=validate_casting_response,
    execute_test=execute_test,
    render_test_entry=render_test_entry,
    render_onboarding_section=render_onboarding_section,
)
